feat: save user details
The-Social-Guardians/Tweet-Guard-Backend pull request #8
Opened 2022-08-10 11:02 UTC by Dun-sin

## closes #4 

## changes proposed
- save users to database

2022-08-10 21:02 UTC, mathiasayivor requested changes

2022-08-10 21:02 UTC, mathiasayivor commented on src/PassportStrategies/Twitter.js
> +                UserModel.findById({twitterId: profile.id}, (error, user) => {
Why not `UserModel.findOne`?
Also, you need to pass the rest of the data when registering; currently, you're only passing twitterId.

2022-08-10 22:25 UTC, A-BMT02 commented
Hey @Dun-sin Just a couple of corrections

- If findById returns error , it doesnt mean that the user does not exists. It is usually a connection problem or something like that
- I suggest you wrap everyting in a try-catch block so it will be easier to handle errors later on
- To check if the user exists you could do something like this
```
try {
const userExists = await UserModel.findOne({twitterId: profile.id})
if(userExists) {
    return cb(null, userExists.lean())
} else {
  //user doesnt exists
  //Here you should create the 'UserModel' document based on the schema in /src/Models/UserModel
  //It would look something like this
  cons newUser = UserModel.create({
  twitterInfo : {
      id : profile.id
      username : profile.something , 
     displayName : profile.something , 
     pictureSrc : profil.something
  }, 
  registeredAt : (Generate current date)
  })
  //after saving the user , you should also save the tokens in the UserAccessTokenModel 
  //same thing as above but use the schema in src/Models/UserAccessTokenModel
  ...
return cb(null , newUser.Json())
}
} catch (error) {
//we'll make error handling a separate issue , for now just call cb(error)
return cb(error) //passport handles all our errors , if there is any error in the try block , the 'failureRedirect' (line 33 in index.js) will be called
}
```

2022-08-11 03:11 UTC, Dun-sin commented on src/PassportStrategies/Twitter.js
> +                UserModel.findById({twitterId: profile.id}, (error, user) => {
Id is unique right? That's why I didn't bother with the rest I guess

2022-08-11 10:07 UTC, A-BMT02 commented on src/PassportStrategies/Twitter.js
> +                UserModel.findById({twitterId: profile.id}, (error, user) => {
I think he meant when creating the new user , you should save the rest of the data too 
He didnt mean you should use all the data to find the user  ,for that the twitter id is enough

2022-08-11 10:09 UTC, closed without merging

2022-08-11 10:12 UTC, Dun-sin commented on src/PassportStrategies/Twitter.js
> +                UserModel.findById({twitterId: profile.id}, (error, user) => {
oh yeah that makes sense

2022-08-11 10:15 UTC, A-BMT02 commented on src/PassportStrategies/Twitter.js
> +                    const newUser = UserModel.create({
When creating the newUser , save all the rest of the data too , not just the twitterId

2022-08-11 10:16 UTC, Dun-sin commented on src/PassportStrategies/Twitter.js
> +                    const newUser = UserModel.create({
yeha got that